name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    container: genhoi/php-unit:7.4-ubuntu
    services:
      rabbitmq:
        image: rabbitmq:alpine
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run tests on amqp-extension
      run: export HUMUS_AMQP_BUNDLE_TEST_DRIVER=amqp-extension && composer run-script test
    - name: Run tests on php-amqplib
      run: export HUMUS_AMQP_BUNDLE_TEST_DRIVER=php-amqplib && composer run-script test
